package kahwei.com.dm2230_mgp.Weapon;

import android.graphics.Bitmap;

import java.util.ArrayList;
import java.util.Random;

/**
 * Created by xecli on 12/5/2015.
 */
public class Weapon
{
    private static Random RNG = new Random();
    public static final int MAX_POWER_LEVEL = 3;
    // The time since the last shot
    private float m_deltaShots = 0.0f;
    // The texture of bullets generated by this weapon
    protected Bitmap m_bulletTex[];
    // Power Level of the Weapon
    private int m_powerLevel = 0;
    protected SubWeapon m_weaponStates[];

    public Weapon()
    {
        // Initialize the Texture Array
        m_bulletTex = new Bitmap[MAX_POWER_LEVEL];

        // Create the subweapon states
        m_weaponStates = new SubWeapon[MAX_POWER_LEVEL];
        m_weaponStates[0] = new SubWeapon();
        m_weaponStates[1] = new SubWeapon();
        m_weaponStates[2] = new SubWeapon();
    }

    public void Update(final double deltaTime)
    {
        m_deltaShots += deltaTime;
    }

    public boolean Shoot()
    {
        if (m_deltaShots > m_weaponStates[m_powerLevel].GetFireRate())
        {
            m_deltaShots = 0.0f;
            return true;
        }

        return false;
    }


    public void ResetLevel()
    {
        m_powerLevel = 1;
    }

    public void LevelUp()
    {
        m_powerLevel = ++m_powerLevel;

        if (m_powerLevel >= MAX_POWER_LEVEL)
        {
            m_powerLevel = MAX_POWER_LEVEL - 1;
        }
    }

    public Bitmap GetBulletTexture()
    {
        return m_bulletTex[m_powerLevel];
    }

    public int GetPowerLevel()
    {
        return m_powerLevel;
    }

    public ArrayList<ShotData> GetShotDatas()
    {
        return m_weaponStates[m_powerLevel].m_shotDatas;
    }
}